import React from "react";
import "bootstrap/dist/js/bootstrap.min.js";

interface CarouselItem {
  src: string;
  alt?: string;
}

interface CarouselProps {
  items: CarouselItem[];
  interval?: number;
}

const Carousel: React.FC<CarouselProps> = ({ items, interval = 3000 }) => {
  //in colaboration with genAi
  const carouselId = `carousel-${Math.random().toString(36).substring(2, 9)}`; //custom ID, incolaboration with genAI

  return (
    <div
      id={carouselId}
      className="carousel slide carousel-fade"
      data-bs-ride="carousel"
    >
      <div className="carousel-inner">
        //generated by genAI
        {items.map((item, index) => (
          <div
            className={`carousel-item${index === 0 ? " active" : ""}`}
            key={index}
            data-bs-interval={interval}
          >
            <img
              src={item.src}
              className="d-block w-100"
              alt={item.alt || `Slide ${index + 1}`}
            />
          </div>
        ))}
      </div>

      {items.length > 1 && ( //generated by genAI
        <>
          <button
            className="carousel-control-prev"
            type="button"
            data-bs-target={`#${carouselId}`}
            data-bs-slide="prev"
          >
            <span className="carousel-control-prev-icon" aria-hidden="true" />
            <span className="visually-hidden">Previous</span>
          </button>
          <button
            className="carousel-control-next"
            type="button"
            data-bs-target={`#${carouselId}`}
            data-bs-slide="next"
          >
            <span className="carousel-control-next-icon" aria-hidden="true" />
            <span className="visually-hidden">Next</span>
          </button>
        </>
      )}
    </div>
  );
};

export default Carousel;
