import { useState } from "react";

function StarRating() {
  const [rating, setRating] = useState(0);
  const [hover, setHover] = useState(0);

  return (
    //generated by genAI
    <div className="d-flex align-items-center">
      {[1, 2, 3, 4, 5].map((star) => (
        <button
          key={star}
          type="button"
          className="btn p-1 border-0 bg-transparent"
          onClick={() => {
            setRating(star);
          }}
          onMouseEnter={() => setHover(star)}
          onMouseLeave={() => setHover(0)}
        >
          <i
            className={`bi ${
              star <= (hover || rating) ? "bi-star-fill" : "bi-star"
            } text-warning fs-4`}
          ></i>
        </button>
        //generated by genAI
      ))}
    </div>
  );
}

export default StarRating;
